/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import CRUD.CRUDLista_Empleados_Zona;
import CRUD.CRUDZona;
import entitys.Lista_Empleados_Zona;
import entitys.Zona;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.TableModel;

/**
 *
 * @author obeth
 */
public class FrmLista_Empleado_Zona extends javax.swing.JFrame {

    private CRUDLista_Empleados_Zona qLista = new CRUDLista_Empleados_Zona();
    List<Lista_Empleados_Zona> lisEmpZon = new ArrayList();
    /**
     * Creates new form FrmLista_Empleado_Zona
     */
    public FrmLista_Empleado_Zona() {
        initComponents();
        setLocationRelativeTo(null);
        llenarTablaListaZona();
    }
    public void llenarTablaListaZona(){
        lisEmpZon = qLista.getListaEmpleadosZona("", "");
        TableModel modelo = qLista.listToTableModel(lisEmpZon);
        tbListaEmpleadosZona.setModel(modelo);
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbListaEmpleadosZona = new javax.swing.JTable();
        btnRegresarMain = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbListaEmpleadosZona.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbListaEmpleadosZona);

        btnRegresarMain.setText("Regresar");
        btnRegresarMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarMainActionPerformed(evt);
            }
        });

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(btnRegresarMain)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAgregar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(btnRegresarMain))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarMainActionPerformed
        // TODO add your handling code here:\
        Main frmM = new Main();
        frmM.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarMainActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        FrmLista_Empleado_Zona frmlist = new FrmLista_Empleado_Zona();
        frmlist.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAgregarActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnRegresarMain;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbListaEmpleadosZona;
    // End of variables declaration//GEN-END:variables
}
