/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista.Insert;

import CRUD.CRUDPlanta;
import CRUD.CRUDProducto;
import Vista.Prev.FrmProductoPrev;
import entitys.Planta;
import entitys.Producto;
import javax.swing.JOptionPane;

/**
 *
 * @author AlanG2PC
 */
public class FrmProductoInsert extends javax.swing.JFrame {

    /**
     * Creates new form FrmProductoInsert
     */
    FrmProductoPrev F;
    Producto Pr = null;
    Planta Pl = null;
    CRUDPlanta CPl;
    CRUDProducto CPr;

    public FrmProductoInsert(FrmProductoPrev f, Producto producto) {
        initComponents();
        setLocationRelativeTo(null);
        setSize(400, 350);
        panelPlanta.setVisible(false);
        txt_Codigo.setText(producto.getPro_codigo());
        txt_Nombre.setText(producto.getPro_nombre());
        txt_Descripcion.setText(producto.getPro_descripcion());
        txt_Precio.setText(String.valueOf(producto.getPro_precio()));
        txt_Tipo.setText(producto.getPro_tipo());
        F = f;
        Pr = producto;
        CPr = new CRUDProducto();
    }

    public FrmProductoInsert(FrmProductoPrev f, Producto producto, Planta planta) {
        initComponents();
        setLocationRelativeTo(null);
        setSize(400, 640);
        txt_Codigo.setText(producto.getPro_codigo());
        txt_Nombre.setText(producto.getPro_nombre());
        txt_Descripcion.setText(producto.getPro_descripcion());
        txt_Precio.setText(String.valueOf(producto.getPro_precio()));
        txt_Codigo.setText(producto.getPro_codigo());

        txt_Clima.setText(planta.getPla_clima());
        txt_Cuidados.setText(planta.getPla_cuidados());
        txt_Humedad.setText(planta.getPla_humedad());
        txt_Luz.setText(planta.getPla_luz());
        F = f;
        Pr = producto;
        Pl = planta;
        CPr = new CRUDProducto();
        CPl=new CRUDPlanta();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_Codigo = new javax.swing.JLabel();
        txt_Nombre = new javax.swing.JLabel();
        txt_Precio = new javax.swing.JLabel();
        txt_Descripcion = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_Tipo = new javax.swing.JLabel();
        btn_Cancelar = new javax.swing.JButton();
        btn_Confirmar = new javax.swing.JButton();
        panelPlanta = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_Clima = new javax.swing.JLabel();
        txt_Humedad = new javax.swing.JLabel();
        txt_Luz = new javax.swing.JLabel();
        txt_Cuidados = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Código");

        jLabel2.setText("Nombre");

        jLabel3.setText("Precio");

        jLabel4.setText("Descripción");

        txt_Codigo.setText("jLabel5");

        txt_Nombre.setText("jLabel6");

        txt_Precio.setText("jLabel7");

        txt_Descripcion.setText("jLabel8");

        jLabel9.setText("Tipo");

        txt_Tipo.setText("jLabel10");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel9))
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_Tipo)
                    .addComponent(txt_Codigo)
                    .addComponent(txt_Nombre)
                    .addComponent(txt_Precio)
                    .addComponent(txt_Descripcion))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_Codigo))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_Nombre))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_Precio))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_Descripcion))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txt_Tipo))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        btn_Cancelar.setText("Cancelar");
        btn_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CancelarActionPerformed(evt);
            }
        });

        btn_Confirmar.setText("Confirmar");
        btn_Confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ConfirmarActionPerformed(evt);
            }
        });

        jLabel5.setText("Clima");

        jLabel6.setText("Humedad");

        jLabel7.setText("Luz");

        jLabel8.setText("Cuidados");

        txt_Clima.setText("jLabel9");

        txt_Humedad.setText("jLabel10");

        txt_Luz.setText("jLabel11");

        txt_Cuidados.setText("jLabel12");

        javax.swing.GroupLayout panelPlantaLayout = new javax.swing.GroupLayout(panelPlanta);
        panelPlanta.setLayout(panelPlantaLayout);
        panelPlantaLayout.setHorizontalGroup(
            panelPlantaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPlantaLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(panelPlantaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPlantaLayout.createSequentialGroup()
                        .addGroup(panelPlantaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addGap(70, 70, 70)
                        .addGroup(panelPlantaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_Humedad)
                            .addComponent(txt_Luz)
                            .addComponent(txt_Clima)))
                    .addGroup(panelPlantaLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(73, 73, 73)
                        .addComponent(txt_Cuidados)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelPlantaLayout.setVerticalGroup(
            panelPlantaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPlantaLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panelPlantaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_Clima))
                .addGap(18, 18, 18)
                .addGroup(panelPlantaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_Humedad))
                .addGap(18, 18, 18)
                .addGroup(panelPlantaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_Luz))
                .addGap(18, 18, 18)
                .addGroup(panelPlantaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_Cuidados))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(204, Short.MAX_VALUE)
                .addComponent(btn_Cancelar)
                .addGap(18, 18, 18)
                .addComponent(btn_Confirmar)
                .addGap(10, 10, 10))
            .addComponent(panelPlanta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelPlanta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Cancelar)
                    .addComponent(btn_Confirmar))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ConfirmarActionPerformed
        try {
            CPr.CreateProducto(Pr);
            if(Pl!=null){
                CPl.CreatePlanta(Pl);
            }
            F.dispose();
            new FrmProductoPrev().setVisible(true);
            this.dispose();
            
        } catch (Exception e) {
            System.out.println("Error:"+e);
        }
    }//GEN-LAST:event_btn_ConfirmarActionPerformed

    private void btn_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CancelarActionPerformed
        this.dispose();
        F.setVisible(true);
    }//GEN-LAST:event_btn_CancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmProductoInsert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmProductoInsert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmProductoInsert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmProductoInsert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Cancelar;
    private javax.swing.JButton btn_Confirmar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelPlanta;
    private javax.swing.JLabel txt_Clima;
    private javax.swing.JLabel txt_Codigo;
    private javax.swing.JLabel txt_Cuidados;
    private javax.swing.JLabel txt_Descripcion;
    private javax.swing.JLabel txt_Humedad;
    private javax.swing.JLabel txt_Luz;
    private javax.swing.JLabel txt_Nombre;
    private javax.swing.JLabel txt_Precio;
    private javax.swing.JLabel txt_Tipo;
    // End of variables declaration//GEN-END:variables
}
