/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista.Prev;

import Vista.Insert.FrmProductoInsert;
import entitys.Planta;
import entitys.Producto;
import javax.swing.JOptionPane;

/**
 *
 * @author AlanG2PC
 */
public class FrmProductoPrev extends javax.swing.JFrame {

    /**
     * Creates new form FrmProductoPrev
     */
    public FrmProductoPrev() {
        initComponents();
        setLocationRelativeTo(null);
        panelPlanta.setVisible(false);
        setSize(400, 420);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrp_Tipo = new javax.swing.ButtonGroup();
        panelProducto = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_Descripcion = new javax.swing.JTextArea();
        txt_Codigo = new javax.swing.JTextField();
        txt_Nombre = new javax.swing.JTextField();
        txt_Precio = new javax.swing.JTextField();
        Planta = new javax.swing.JLabel();
        cb_Tipo = new javax.swing.JComboBox<>();
        panelPlanta = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_Clima = new javax.swing.JTextField();
        txt_Humedad = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_Cuidados = new javax.swing.JTextArea();
        cb_Luz = new javax.swing.JComboBox<>();
        btn_Cancelar = new javax.swing.JButton();
        btn_Confirmar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Código");

        jLabel2.setText("Descripción");

        jLabel3.setText("Precio");

        jLabel4.setText("Nombre");

        jLabel5.setText("Ingresar Producto");

        txt_Descripcion.setColumns(20);
        txt_Descripcion.setRows(5);
        txt_Descripcion.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txt_Descripcion);

        Planta.setText("Tipo");

        cb_Tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Accesorios", "Jardinería", "Planta" }));
        cb_Tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_TipoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelProductoLayout = new javax.swing.GroupLayout(panelProducto);
        panelProducto.setLayout(panelProductoLayout);
        panelProductoLayout.setHorizontalGroup(
            panelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelProductoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(177, 177, 177))
            .addGroup(panelProductoLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(panelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(Planta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(txt_Codigo)
                    .addComponent(txt_Nombre)
                    .addComponent(txt_Precio)
                    .addComponent(cb_Tipo, 0, 180, Short.MAX_VALUE))
                .addGap(30, 30, 30))
        );
        panelProductoLayout.setVerticalGroup(
            panelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProductoLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel5)
                .addGap(28, 28, 28)
                .addGroup(panelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_Precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_Tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Planta))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jLabel6.setText("Clima");

        jLabel7.setText("Humedad");

        jLabel8.setText("Luz");

        jLabel9.setText("Cuidados");

        txt_Cuidados.setColumns(20);
        txt_Cuidados.setRows(5);
        jScrollPane2.setViewportView(txt_Cuidados);

        cb_Luz.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Muy baja", "Baja", "Media", "Alta" }));

        javax.swing.GroupLayout panelPlantaLayout = new javax.swing.GroupLayout(panelPlanta);
        panelPlanta.setLayout(panelPlantaLayout);
        panelPlantaLayout.setHorizontalGroup(
            panelPlantaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPlantaLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(panelPlantaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addGroup(panelPlantaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_Humedad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Clima, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_Luz, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );
        panelPlantaLayout.setVerticalGroup(
            panelPlantaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPlantaLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(panelPlantaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_Clima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(panelPlantaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_Humedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelPlantaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cb_Luz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(panelPlantaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        btn_Cancelar.setText("Cancelar");

        btn_Confirmar.setText("Confirmar");
        btn_Confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ConfirmarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelPlanta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_Cancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Confirmar)
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelPlanta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Confirmar)
                    .addComponent(btn_Cancelar))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ConfirmarActionPerformed
        String mensajeError = "";
        float precio = 0;
        if (txt_Codigo.getText() == null || "".equals(txt_Codigo.getText()) || "".equals(txt_Codigo.getText().trim()) || txt_Codigo.getText().length() < 4 || !txt_Codigo.getText().matches("\\d+")) {
            mensajeError += "Debe ingresar un código de inventario (4 dígitos)\n";
        }
        if (txt_Precio.getText() == null || "".equals(txt_Precio.getText()) || "".equals(txt_Precio.getText().trim()) || txt_Precio.getText().length() < 1 || !txt_Precio.getText().matches("\\d*\\.?\\d*")) {
            mensajeError += "Debe ingresar una cantidad para precio (solo números)\n";
        } else {
            precio = Float.parseFloat(txt_Precio.getText());
            if (precio < 1) {
                mensajeError += "Debe ingresar un precio mayor a $1.0\n";
            }
        }
        if (txt_Nombre.getText() == null || "".equals(txt_Nombre.getText()) || "".equals(txt_Nombre.getText().trim()) || txt_Nombre.getText().length() < 4) {
            mensajeError += "Debe ingresar un nombre de producto de al menos 4 caracteres\n";
        }
        if (txt_Descripcion.getText() == null || "".equals(txt_Descripcion.getText()) || "".equals(txt_Descripcion.getText().trim()) || txt_Descripcion.getText().length() < 4) {
            mensajeError += "La descripción no puede estar vacía\n";
        }
        if ("Planta".equals(cb_Tipo.getSelectedItem().toString())) {
            if (txt_Clima.getText() == null || "".equals(txt_Clima.getText()) || "".equals(txt_Clima.getText().trim()) || txt_Clima.getText().length() < 4) {
                mensajeError += "Ingrese clima (al menos 4 caracteres)\n";
            }
            if (txt_Humedad.getText() == null || "".equals(txt_Humedad.getText()) || "".equals(txt_Humedad.getText().trim()) || txt_Humedad.getText().length() < 4) {
                mensajeError += "El campo humedad no puede estar vacío\n";
            }
            if (cb_Luz.getSelectedIndex() == -1) {
                mensajeError += "Seleccione nivel de luz\n";
            }
            if (txt_Cuidados.getText() == null || "".equals(txt_Cuidados.getText()) || "".equals(txt_Cuidados.getText().trim()) || txt_Cuidados.getText().length() < 4) {
                mensajeError += "La descripción de cuidados no puede estar vacía\n";
            }
        }
        if ("".equals(mensajeError)) {
            Producto producto = new Producto(txt_Codigo.getText(), txt_Nombre.getText(), txt_Descripcion.getText(), cb_Tipo.getSelectedItem().toString(), precio);
            if ("Planta".equals(cb_Tipo.getSelectedItem().toString())) {
                Planta planta= new Planta(txt_Nombre.getText(),txt_Clima.getText(),txt_Cuidados.getText(),txt_Humedad.getText(),cb_Luz.getSelectedItem().toString());
                new FrmProductoInsert(this,producto,planta).setVisible(true);
                this.setVisible(false);
            } else {
                new FrmProductoInsert(this, producto).setVisible(true);
                this.setVisible(false);
            }

        } else {
            JOptionPane.showMessageDialog(null, mensajeError, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_ConfirmarActionPerformed

    private void cb_TipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_TipoActionPerformed
        if ("Planta".equals(cb_Tipo.getSelectedItem().toString())) {
            panelPlanta.setVisible(true);
            setSize(400, 620);

        } else {
            panelPlanta.setVisible(false);
            setSize(400, 420);
        }
    }//GEN-LAST:event_cb_TipoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmProductoPrev.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmProductoPrev.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmProductoPrev.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmProductoPrev.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmProductoPrev().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Planta;
    private javax.swing.ButtonGroup btnGrp_Tipo;
    private javax.swing.JButton btn_Cancelar;
    private javax.swing.JButton btn_Confirmar;
    private javax.swing.JComboBox<String> cb_Luz;
    private javax.swing.JComboBox<String> cb_Tipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panelPlanta;
    private javax.swing.JPanel panelProducto;
    private javax.swing.JTextField txt_Clima;
    private javax.swing.JTextField txt_Codigo;
    private javax.swing.JTextArea txt_Cuidados;
    private javax.swing.JTextArea txt_Descripcion;
    private javax.swing.JTextField txt_Humedad;
    private javax.swing.JTextField txt_Nombre;
    private javax.swing.JTextField txt_Precio;
    // End of variables declaration//GEN-END:variables
}
